name: 'Fasterer with reviewdog'
description: '🐶 Run fasterer with reviewdog on pull requests to improve code review experience.'
author: 'vk26'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  fasterer_version:
    description: 'Fasterer version'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'fasterer'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: 'Filtering mode for the reviewdog command [added,diff_context,file,nofilter]'
    default: 'nofilter'
  fail_on_error:
    description: 'Exit code for reviewdog when errors are found [true,false]'
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Run fasterer with reviewdog
      shell: sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_FASTERER_VERSION: ${{ inputs.fasterer_version }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
      run: |
        ${{ github.action_path }}/entrypoint.sh
branding:
  icon: 'check-circle'
  color: 'red'
