name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reviewdog-fasterer:$(date +%s)
